#Test set, 2080ti
python batch_nlp_caption.py --parquet_path "H:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:0" --fp16 --prompt_threads 48 --img_dir "H:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "./missing.json" --out_json_good "./meta_cap_2024_toriigate_good.json" --out_json_bad "./meta_cap_2024_toriigate_bad.json" --start_index 3075 --end_index 3079
#Prod set, 3090x4
python batch_nlp_caption.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:0" --model_id "Minthy/ToriiGate-v0.4-7B" --prompt_threads 6 --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_4.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_4.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_4.json"
python batch_nlp_caption.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:1" --model_id "Minthy/ToriiGate-v0.4-7B" --prompt_threads 6 --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_5.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_5.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_5.json"
python batch_nlp_caption.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:2" --model_id "Minthy/ToriiGate-v0.4-7B" --prompt_threads 6 --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_6.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_6.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_6.json" 
python batch_nlp_caption.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:3" --model_id "Minthy/ToriiGate-v0.4-7B" --prompt_threads 6 --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_7.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_7.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_7.json"

#Test set, 3090, exl
python batch_nlp_caption_exl.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:0" --model_local_path "C:/Users/User/.cache/huggingface/hub/models--Minthy--ToriiGate-v0.4-7B-exl2-4bpw/snapshots/6cdb5c87ef8bcc2e23f143b690c542358cfd72a8" --img_dir "F:/just_astolfo/_test/" --in_json "./test_ids.json" --out_json_good "./exl_good_4.json" --out_json_bad "./exl_bad_4.json"
python batch_nlp_caption_exl.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:0" --model_local_path "C:/Users/User/.cache/huggingface/hub/models--Minthy--ToriiGate-v0.4-7B-exl2-8bpw/snapshots/db4ff9e988b09765c98d9ef5485afeb60a0054e6" --img_dir "F:/just_astolfo/_test/" --in_json "./test_ids.json" --out_json_good "./exl_good_8.json" --out_json_bad "./exl_bad_8.json"

#Prod set, 3090x4, exl
python batch_nlp_caption_exl.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:0" --prompt_threads 6 --model_local_path "C:/Users/User/.cache/huggingface/hub/models--Minthy--ToriiGate-v0.4-7B-exl2-8bpw/snapshots/db4ff9e988b09765c98d9ef5485afeb60a0054e6" --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_0.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_0.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_0.json"
python batch_nlp_caption_exl.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:1" --prompt_threads 6 --model_local_path "C:/Users/User/.cache/huggingface/hub/models--Minthy--ToriiGate-v0.4-7B-exl2-8bpw/snapshots/db4ff9e988b09765c98d9ef5485afeb60a0054e6" --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_1.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_1.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_1.json"
python batch_nlp_caption_exl.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:2" --prompt_threads 6 --model_local_path "C:/Users/User/.cache/huggingface/hub/models--Minthy--ToriiGate-v0.4-7B-exl2-8bpw/snapshots/db4ff9e988b09765c98d9ef5485afeb60a0054e6" --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_2.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_2.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_2.json" 
python batch_nlp_caption_exl.py --parquet_path "F:/danbooru2024-webp-4Mpixel/metadata.parquet" --device "cuda:3" --prompt_threads 6 --model_local_path "C:/Users/User/.cache/huggingface/hub/models--Minthy--ToriiGate-v0.4-7B-exl2-8bpw/snapshots/db4ff9e988b09765c98d9ef5485afeb60a0054e6" --img_dir "F:/danbooru2024-webp-4Mpixel/kohyas_finetune/" --in_json "F:/tipo-toriigate-runtime/split_files/missing_3.json" --out_json_good "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_good_3.json" --out_json_bad "F:/tipo-toriigate-runtime/split_files/meta_cap_2024_toriigate_bad_3.json"
