python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_0.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_0.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 180
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_1.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_1.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:1" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 120
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_2.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_2.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:2" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 60
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_3.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_3.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:3" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 0
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_4.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_4.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 180
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_5.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_5.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:1" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 120
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_6.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_6.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:2" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 60
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_7.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_7.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:3" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 0
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_8.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_8.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 180
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_9.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_9.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:1" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 120
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_10.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_10.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:2" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 60
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_11.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_11.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:3" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 0 --delay_start 0
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_12.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_12.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 453000 --delay_start 180
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_13.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_13.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:1" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 458000 --delay_start 120
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_14.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_14.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:2" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 482000 --delay_start 60
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_15.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_15.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:3" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_data_loader_n_workers 2 --max_resolution "1024,1024" --mixed_precision "fp16" --start_from_index 436000 --delay_start 0
#
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_0.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_0.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_1.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_1.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_2.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_2.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_3.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_3.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_4.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_4.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_5.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_5.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_6.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_6.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_7.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_7.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_8.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_8.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_9.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_9.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_10.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_10.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_11.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_11.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_12.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_12.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_13.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_13.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_14.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_14.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"
python ./finetune/prepare_buckets_latents_v2.py "H:/danbooru2024-webp-4Mpixel/kohyas_finetune" "H:/danbooru2024-webp-4Mpixel/meta_cap_dd_15.json" "H:/danbooru2024-webp-4Mpixel/meta_lat_15.json" "E:/NOVELAI/stable-diffusion-webui/stable-diffusion-webui/models/VAE/sdxl-vae-fp16-fix.vae.safetensors" --vae_device "cuda:0" --no_listdir --image_ext_static ".webp" --skip_existing --batch_size 1 --max_resolution "1024,1024" --mixed_precision "fp16"

IF EXIST "H:/danbooru2024-webp-4Mpixel/kohyas_finetune/1566802.npz" (echo "1566802") 
IF EXIST "H:/danbooru2024-webp-4Mpixel/kohyas_finetune/1570434.npz" (echo "1570434") 