model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "E:/kuake/sd-webui-aki/sd-webui-aki-v4.8/models/Stable-diffusion/noobaiXLNAIXL_epsilonPred05Version.safetensors"
vae = "E:/kuake/sd-webui-aki/sd-webui-aki-v4.8/models/VAE/sdxl_vae.safetensors"
train_data_dir = "./train/aki"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 640
max_bucket_reso = 1536
bucket_reso_steps = 32
output_name = ""
output_dir = ""
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = 6
train_batch_size = 2
gradient_checkpointing = true
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0004
unet_lr = 0.0004
text_encoder_lr = 0.00001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdaFactor"
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
weighted_captions = false
keep_tokens = 0
max_token_length = 255
seed = 1337
mixed_precision = "fp16"
full_fp16 = true
fp8_base = false
xformers = true
lowram = true
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
persistent_data_loader_workers = true